#ifndef SERIALMONITOR_GLOBAL_H
#define SERIALMONITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALMONITOR_LIBRARY)
#  define SERIALMONITOR_EXPORT Q_DECL_EXPORT
#else
#  define SERIALMONITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALMONITOR_GLOBAL_H
